name: NextGenBedwars
description: The next-generation plugin for BedWars.
version: '${version}'

main: top.earthstudio.nextgenbedwars.NextGenBedwars
api-version: '1.21'
load: POSTWORLD

authors: [ Earth Studio ]
